title: Chronos Security
subtitle: Sharing knowledge
description: CTFs, writeups, cheatsheets, and explanations in cybersecurity
keywords: null
author: "ChronosPK | Marin Radu"
language: en
timezone: 'Europe/Bucharest'
url: https://chronossec.site
permalink: ':title/'
permalink_defaults: null
pretty_urls:
  trailing_index: true
  trailing_html: true
source_dir: source
public_dir: public
tag_dir: tags
# archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: ':lang'
skip_render: null
new_post_name: ':title.md'
default_layout: post
titlecase: false
external_link:
  enable: true
  field: site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  enable: true
  # engine: highlight
  theme: tomorrow-night-blue
  line_number: false
  clipboard: true
  auto_detect: false
  tab_replace: '  '
  wrap: false
  hljs: true
prismjs:
  enable: false
  # preprocess: true
  # line_number: false
  # tab_replace: '  '
index_generator:
  path: ''
  per_page: 0
  order_by: 'name'
default_category: uncategorized
category_map: null
tag_map: null
meta_generator: true
date_format: DD-MM-YYYY
time_format: HH:mm:ss
# updated_option: mtime
per_page: 0
pagination_dir: page
include: null
exclude: null
ignore: null
theme: next # landscape, icarus, next, arknights
toc:
  maxdepth: 2
  depth: 1
  class: toc
  slugify: transliteration
  decodeEntities: false
  anchor:
    position: after
    symbol: '#'
    style: header-anchor
# Generate categories from directory-tree
# Dependencies: https://github.com/xu-song/hexo-auto-category
auto_category:
 enable: true
 multiple: true
 depth: 2
deploy:
  type: git
  repo: git@github.com:ChronosPK/chronospk.github.io
  branch: main
  message: "Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}"